# გამოვიყენოთ ნოუდის მეოცე ვერსია, რომლეიც დაყენებულია bullseye სერვერზე
FROM node:22-bullseye

# ავირჩიოთ აპლიკაციისთვის სამუშაო დირექტორია
WORKDIR /usr/src/app

# გადმოვაკოპიროთ package.json ./ში
COPY package*.json ./

# გავუშვათ npm install
RUN npm install

# გადმოვაკოპიროთ დანარჩენი აპლიკაცია კომპიუტერიდან
COPY . .

# გავბილდოთ nestjs
RUN npm run build

# გავხსნათ პორტი 3000
EXPOSE 3000

# დავსტარტოთ აპლიკაცია
CMD ["npm", "run", "start:prod"]
